name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite execução manual

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar estrutura do repositório
        run: ls -R

      - name: Executa os Testes de Performance
        uses: QAInsights/PerfAction@v5.6.2
        with:
            test-plan-path: ./tests/amazon_test.jmx
            args: ""

      - name: Publica os Relatórios como Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error